name: fluttron_cli
description: Command-line tool for creating, building, and running Fluttron applications.
version: 0.1.0-alpha
publish_to: none
repository: https://github.com/maxiee/Fluttron

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  analyzer: ^10.0.2
  args: ^2.7.0
  fluttron_shared:
    path: ../fluttron_shared
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  fluttron: fluttron
