name: fluttron_cli
description: Fluttron command-line interface.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  fluttron: fluttron
