name: markdown_editor_ui
description: "UI project for the markdown_editor example."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_ui:
    path: ../../../packages/fluttron_ui
  fluttron_shared:
    path: ../../../packages/fluttron_shared
  fluttron_milkdown:
    path: ../../../web_packages/fluttron_milkdown
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
