name: template_service_host
description: "Host-side implementation of template_service for Fluttron."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  fluttron_host:
    path: ../../../packages/fluttron_host
  fluttron_shared:
    path: ../../../packages/fluttron_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
