name: fluttron_web_package_template
description: "Template for creating reusable Fluttron web packages."

version: 0.1.0
publish_to: none

# This tag identifies the package as a Fluttron web package.
# The CLI will scan dependencies for this tag to discover web packages.
fluttron_web_package: true

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_ui:
    path: ../../packages/fluttron_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
