name: host_service_demo_host
description: "Host app demonstrating custom service integration."
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_host:
    path: ../../../packages/fluttron_host
  fluttron_shared:
    path: ../../../packages/fluttron_shared

dev_dependencies:
  flutter_lints: ^6.0.0
