name: fluttron_ui_app
description: "Fluttron UI template app."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_ui:
    path: ../../packages/fluttron_ui
  fluttron_shared:
    path: ../../packages/fluttron_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
