name: fluttron_host_app
description: "Fluttron host template app."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_host:
    path: ../../packages/fluttron_host
  fluttron_shared:
    path: ../../packages/fluttron_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/www/
    - assets/www/ext/
    - assets/www/ext/packages/
    - assets/www/assets/
    - assets/www/assets/fonts/
    - assets/www/assets/packages/cupertino_icons/assets/
    - assets/www/canvaskit/
