name: fluttron_host
description: "Fluttron Host runtime â€” WebView container, service registry, and built-in services."
publish_to: 'none'

version: 0.1.0-alpha

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_shared:
    path: ../fluttron_shared
  flutter_inappwebview: ^6.1.5
  cupertino_icons: ^1.0.8
  file_selector: ^1.0.3
  window_manager: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/www/
    - assets/www/assets/
    - assets/www/assets/fonts/
    - assets/www/assets/packages/cupertino_icons/assets/
    - assets/www/canvaskit/

