name: host_service_demo_ui
description: "UI app demonstrating custom service integration."
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluttron_ui:
    path: ../../../packages/fluttron_ui

dev_dependencies:
  flutter_lints: ^6.0.0
